/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as GoodsProductIdRouteImport } from './routes/goods/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsProductIdRoute = GoodsProductIdRouteImport.update({
  id: '/goods/$productId',
  path: '/goods/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goods/$productId': typeof GoodsProductIdRoute
  '/cart/': typeof CartIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/live/': typeof LiveIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goods/$productId': typeof GoodsProductIdRoute
  '/cart': typeof CartIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/live': typeof LiveIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goods/$productId': typeof GoodsProductIdRoute
  '/cart/': typeof CartIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/live/': typeof LiveIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goods/$productId'
    | '/cart/'
    | '/discover/'
    | '/live/'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goods/$productId' | '/cart' | '/discover' | '/live' | '/search'
  id:
    | '__root__'
    | '/'
    | '/goods/$productId'
    | '/cart/'
    | '/discover/'
    | '/live/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoodsProductIdRoute: typeof GoodsProductIdRoute
  CartIndexRoute: typeof CartIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods/$productId': {
      id: '/goods/$productId'
      path: '/goods/$productId'
      fullPath: '/goods/$productId'
      preLoaderRoute: typeof GoodsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoodsProductIdRoute: GoodsProductIdRoute,
  CartIndexRoute: CartIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
